# -*- coding: utf-8 -*-
"""Modul_penjumlahan.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PNcyoKYq_GrP4uFG-G5T1avDlRrCHIGt
"""

def penjumlahan(angka_1,angka_2):
  jumlah = angka_1 + angka_2
  return jumlah